# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 06:50
from __future__ import unicode_literals

import dirtyfields.dirtyfields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darshans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rituals', models.CharField(default=None, max_length=250)),
                ('timings', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_No', models.CharField(blank=True, max_length=15, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=None, null=True)),
                ('width_field', models.IntegerField(blank=True, default=None, null=True)),
                ('TimeD', models.TimeField(blank=True, null=True)),
                ('publish', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temple1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('selected', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None), blank=True, default=list, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple2', models.CharField(default=None, max_length=250)),
                ('Iconimages', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('images', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=None, null=True)),
                ('width_field', models.IntegerField(blank=True, default=None, null=True)),
                ('Religion', models.CharField(default=None, max_length=200)),
                ('Address', models.TextField(default=None)),
                ('City', models.CharField(default=None, max_length=40)),
                ('State', models.CharField(default=None, max_length=50)),
                ('Country', models.CharField(default=None, max_length=60)),
                ('Deity', models.CharField(default=None, max_length=100)),
                ('Website', models.URLField(default=None)),
                ('LiveDarshan', models.BooleanField(default=False)),
                ('LiveDarshanlink', models.URLField(blank=True, default=None)),
                ('OnlineDonationStatus', models.BooleanField(default=False)),
                ('OnlineDonation', models.URLField(blank=True, default=None)),
                ('LivePooja', models.BooleanField(default=False)),
                ('OnlinePooja', models.URLField(blank=True, default=None)),
                ('OnlinePrasadStatus', models.BooleanField(default=False)),
                ('OnlinePrasad', models.URLField(blank=True, default=None)),
                ('OtherOnlineFacilityStatus', models.BooleanField(default=False)),
                ('OtherOnlineFacility', models.URLField(blank=True, default=None)),
                ('Contacts', models.CharField(default=None, max_length=300)),
                ('PhoneNumber', models.CharField(default=None, max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('AboutTemple', models.TextField(default=None)),
                ('TempleHistory', models.TextField(default=None)),
                ('TemplePurohit', models.CharField(default=None, max_length=250)),
                ('Significance', models.TextField(default=None)),
                ('Management', models.TextField(default=None)),
                ('RelatedFaith', models.TextField(default=None)),
                ('AboutCity', models.TextField(default=None)),
                ('HowToReach', models.TextField(default=None)),
                ('DoAndDont', models.TextField(default=None)),
                ('Amenities', models.TextField(default=None)),
                ('Celebration', models.TextField(default=None)),
                ('PrecautionWhileVisiting', models.TextField(default=None)),
                ('Tender', models.TextField(blank=True, default=None)),
                ('Recruitment', models.TextField(blank=True, default=None, null=True)),
                ('NoticeandUpdates', models.TextField(blank=True, default=None, null=True)),
                ('Accomodation', models.BooleanField(default=False)),
                ('AccomodationLink', models.URLField(blank=True, default=None)),
                ('Annakshetra', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['temple2'],
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='Temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darshan.Temples'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='darshans',
            name='temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darshan.Temples'),
        ),
    ]
