# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 06:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_No', models.CharField(blank=True, max_length=15, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=None, null=True)),
                ('width_field', models.IntegerField(blank=True, default=None, null=True)),
                ('TimeD', models.TimeField(blank=True, null=True)),
                ('publish', models.DateField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temple1', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
                ('selected', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None), blank=True, default=list, null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple2', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='Temple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darshan.Temples'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
