# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temples',
            name='Address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='temples',
            name='City',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='temples',
            name='Contacts',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='temples',
            name='Country',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='temples',
            name='Deity',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='temples',
            name='Email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='temples',
            name='LiveDarshanStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temples',
            name='LiveDarshanlink',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='temples',
            name='OnlineDonation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temples',
            name='OnlinePooja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temples',
            name='OnlinePrasad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temples',
            name='OtherOnlineFacility',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='temples',
            name='PhoneNumber',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='temples',
            name='Religion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='temples',
            name='State',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='temples',
            name='Website',
            field=models.URLField(default=None),
        ),
    ]
