# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0002_auto_20180522_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temples',
            name='OnlineDonation',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePooja',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePrasad',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OtherOnlineFacility',
            field=models.URLField(default=None),
        ),
    ]
