# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0003_onlinedonation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Temple1',
            new_name='Select_Temple',
        ),
    ]
