# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0003_auto_20180522_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temples',
            name='LiveDarshanlink',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlineDonation',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePooja',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePrasad',
            field=models.URLField(blank=True, default=None),
        ),
    ]
