# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0004_auto_20180522_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='temples',
            name='height_field',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='temples',
            name='images',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='temples',
            name='width_field',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
