# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0005_templemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templemanager',
            old_name='Temple_selected',
            new_name='Temple_Name',
        ),
    ]
