# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0006_auto_20180615_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templemanager',
            old_name='manager',
            new_name='user',
        ),
    ]
