# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0007_auto_20180615_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temples',
            old_name='OtherOnlineFacility',
            new_name='OnlineFacility',
        ),
    ]
