# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darshan', '0008_auto_20180615_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temples',
            name='OnlineFacility',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePooja',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='temples',
            name='OnlinePrasad',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
