# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darshan', '0009_auto_20180615_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='temples',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
