# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('darshan', '0012_auto_20180616_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='darshans',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
