# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('darshan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=None, null=True)),
                ('width_field', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default=None, max_length=250)),
                ('OutofStock', models.BooleanField(default=False)),
                ('Price', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('Photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=None, null=True)),
                ('width_field', models.IntegerField(blank=True, default=None, null=True)),
                ('OfferorDiscount', models.CharField(blank=True, default=None, max_length=50)),
                ('TempleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darshan.Temples')),
            ],
            options={
                'ordering': ['-Price'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
