# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 06:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=250, null=True), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
