# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180523_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductName',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
