# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 12:54
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productselected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['Price']},
        ),
        migrations.AlterField(
            model_name='productselected',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=None, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
