# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
