# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
