# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180608_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='updated_at',
        ),
    ]
