# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20180608_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
