# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
